apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "rabbitmq"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "rabbitmq"
  template:
    metadata:
      labels:
        app: "rabbitmq"
    spec:
      containers:
        - name: "rabbitmq"
          env:
            - name: "RABBITMQ_DEFAULT_PASS"
              value: "VoltecVoltec7"
            - name: "RABBITMQ_DEFAULT_USER"
              value: "voltec"
          image: "rabbitmq:4-management"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: "rabbitmq"
              mountPath: "/var/lib/rabbitmq"
  volumeClaimTemplates:
    - metadata:
        name: "rabbitmq"
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "4Gi"