apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "mssql"
spec:
  serviceName: "mssql" 
  replicas: 1 
  selector:
    matchLabels:
      app: "mssql"
  template:
    metadata:
      labels:
        app: "mssql"
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: "mssql"
          env:
            - name: "ACCEPT_EULA"
              value: "Y"
            - name: "MSSQL_AGENT_ENABLED"
              value: "1"
            - name: "MSSQL_BACKUP_DIR"
              value: "/var/opt/mssql/backup"
            - name: "MSSQL_ENABLE_HADR"
              value: "1"
            - name: "MSSQL_LCID"
              value: "3082"
            - name: "MSSQL_PID"
              value: "Developer"
            - name: "MSSQL_SA_PASSWORD"
              value: "VoltecVoltec7#"
            - name: "TZ"
              value: "Europe/Madrid"
          image: "mcr.microsoft.com/mssql/server:2025-latest"
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: "mssql"
              mountPath: "/var/opt/mssql"
  volumeClaimTemplates:
    - metadata:
        name: "mssql"
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
